'use strict';
// Deliberately publishable anonymous-equivalent credential, NOT a user or admin token.
// Its cd_gateway role has no private-table access. Every account/save operation
// separately validates a password or an opaque per-user session inside PostgreSQL.
module.exports='eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImNkLXB1YmxpYy1nYXRld2F5LXYxIn0.eyJzdWIiOiJjb3JydXB0LWRyaXZlLXB1YmxpYy1nYXRld2F5Iiwicm9sZSI6ImNkX2dhdGV3YXkiLCJhdWQiOiJjb3JydXB0LWRyaXZlLWdhdGV3YXkiLCJpc3MiOiJodHRwczovL2NvcnJ1cHQtZHJpdmUudmVyY2VsLmFwcCIsImlhdCI6MTc5MDAzNTIwMCwiZXhwIjoxOTQ3NzE1MjAwfQ.N7p0uPHsvj9s1Mc9u_2r3pvsjI88PwcD-WibJl9-hHSIOkSt2tPLUGV-Lbr2j4TPDejOKh4m_9aW0FGHaoK2ZzcqLxBMOAGUhWVrFJKCrB1yxi4oYFrFdKXlIr5XxL0xu6QZT8pwKdVLfDlh_t5BTIQry81vrHoKNRD25a3C-ouopaUNMZwpcWWaPGso7L2jGcWvtmU9Q4KRixPM62erln1abxgsWkoqtS2UVm5yrrSuV2MFHM_l5vbPLqEI2NE9HMWX9NGYQsBc4UBC7432Wmd8fazCAlZWcJr9fI7LAWDjTW7qQygA7XfMaUtud3WFE7m2HM_DcsoWcRxbQU8-Wg';
